### ISSUE TITLE
Extra HTML tags added to prometheus /metrics

### ISSUE THREAD

**Issue by dcherniv** [Kong/kong-plugin-prometheus#38]
When curling /metrics page, it seems prometheus plugin outputs some extra HTML tag that prometheus scraper doesn't like.

```
 curl localhost:10254/metrics
[...]
<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body></body></html>

/tmp/prometheus-2.6.0.linux-amd64 # curl -s http://localhost:10254/metrics/ | tee out | ./promtool check metrics 
error while linting: text format parsing error in line 306: invalid metric name
/tmp/prometheus-2.6.0.linux-amd64 # head -n 306 out |tail -n1
<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body></body></html>/tmp/prometheus-2.6.0.linux-amd64 # 
```
Could this be related https://github.com/leafo/lapis/issues/440

As a result of this the prometheus plugin is not parsing any metrics at all.

**Comment by dcherniv** [comment]
@hbagdi for your consideration

**Comment by hbagdi** [comment]
Which version of Kong are you using?
And how are you accessing the `/metrics` endpoint?

**Comment by dcherniv** [comment]
kong 1.0.0.

metrics is exposed via custom nginx config.
```
server {
  server_name kong_prometheus_exporter;
  listen 0.0.0.0:10254; # can be any other port as well

  location / {
    default_type text/plain;
    content_by_lua_block {
        local serve = require "kong.plugins.prometheus.serve"
        serve.prometheus_server()
    }
  }

  location /nginx_status {
    internal;
    access_log off;
    stub_status;
  }
}
```

**Comment by dcherniv** [comment]
i quickly tested the above PR with my own image.
```
#LATEST_TAG 1.0.0
FROM REDACTED
ENV KONG_VERSION 1.0.0
ENV KONG_SHA256 79001d96c28d774bcf868f281e8e3486c4027ed35d69da6560172a742240b862

RUN apk add --no-cache --virtual .build-deps wget tar ca-certificates \
        && apk add --no-cache libgcc openssl pcre perl tzdata curl \
        && wget -O kong.tar.gz "https://bintray.com/kong/kong-community-edition-alpine-tar/download_file?file_path=kong-community-edition-$KONG_VERSION.apk.tar.gz" \
        && echo "$KONG_SHA256 *kong.tar.gz" | sha256sum -c - \
        && tar -xzf kong.tar.gz -C /tmp \
        && rm -f kong.tar.gz \
        && cp -R /tmp/usr / \
        && rm -rf /tmp/usr \
        && cp -R /tmp/etc / \
        && rm -rf /tmp/etc \
        && apk del .build-deps

COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY serve.lua /usr/local/share/lua/5.1/kong/plugins/prometheus/
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["kong", "docker-start"]
```
serve.lua
```
[...]
app:match("/metrics", function()
  prometheus:collect()
  return { content_type = "text/plain", layout = false, render = true }
end)
[...]
```
and prometheus works like a charm now

**Comment by dcherniv** [comment]
scraper config follows:
```
- job_name: 'ingress-kong-endpoints'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - kong

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2

        - source_labels: [__meta_kubernetes_service_name]
          regex: prometheus-server
          action: drop
```
Annotations on the pod:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
[...]
   name: kong-proxy
    ports:
    - containerPort: 80
      name: proxy
      protocol: TCP
    - containerPort: 443
      name: proxy-ssl
      protocol: TCP
    - containerPort: 10254
      name: proxy-prom
      protocol: TCP
[...]
```
