### ISSUE TITLE
kong-plugin-prometheus Service/Route Metrics error

### ISSUE THREAD

**Issue by xichengliudui** [Kong/kong-plugin-prometheus#64]
https://github.com/Kong/kong-plugin-prometheus/pull/48 has been fixed, but we don't know how to use it, like before?

```
curl http://localhost:8001/plugins -d name=prometheus
```

like this here:

![image](https://user-images.githubusercontent.com/40875627/65142222-d18fbc00-da44-11e9-9a18-b4275ffc9889.png)

```
kong version : 1.3.0rc1
```

prometheus config

```
  - job_name: 'kongapi'
    static_configs:
    - targets: ['10.20.11.117:8001']
      labels:
        group: "kongapi"
```
